runtime: nodejs24

instance_class: F2

automatic_scaling:
  max_instances: 2     # limit to 2 instances
  min_instances: 0     # scale down to 0 when idle
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.75

env_variables:
  NODE_ENV: "production"
  LLM_API: "your-api-key"
  GOOGLE_SPREADSHEET_CLIENT_EMAIL: "your-google-spreadsheet-client-email"
  GOOGLE_DRIVE_CLIENT_EMAIL: "your-google-drive-client-email"
  OCR_GOOGLE_CLIENT_EMAIL: "your-ocr-google-client-email"


handlers:
  # Handlers — ensure all routes (including /api/*) are served by Next.js
  - url: /_next/static
    static_dir: .next/static
    secure: always

  - url: /favicon\.ico
    static_files: public/favicon.ico
    upload: public/favicon\.ico
    secure: always

  - url: /static
    static_dir: public
    secure: always

  - url: /.*
    script: auto
    secure: always