import Header from "@/components/header";
import StepperComponent from "@/components/stepperComponent";
import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";

const dmSans = DM_Sans({
  subsets: ["latin"],
  variable: "--font-dm-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${dmSans.variable} antialiased`}>
        <div className="max-w-fit mx-auto flex flex-col justify-center items-center">
          <Header />
          <StepperComponent />
          {children}
        </div>
      </body>
    </html>
  );
}
